CI: Stack use system ghc

diff --git a/.github/workflows/nix-based-build.yaml b/.github/workflows/nix-based-build.yaml
--- a/.github/workflows/nix-based-build.yaml
+++ b/.github/workflows/nix-based-build.yaml
@@ -39,10 +39,10 @@ jobs:
       - name: Initial nix develop
         run: nix develop --profile .dev-profile -c sh -c 'which stack; which gf; echo $GF_LIB_PATH'
       - name: stack deps
-        run: nix develop --profile .dev-profile -c stack build --no-nix --only-dependencies
+        run: nix develop --profile .dev-profile -c stack build --system-ghc --only-dependencies
       - name: stack build
         # if: ${{ false }}
-        run: nix develop --profile .dev-profile -c sh -c 'stack build --no-nix --test --no-run-tests || echo "::warning file=app.js,line=1,col=5::Failure"'
+        run: nix develop --profile .dev-profile -c sh -c 'stack build --system-ghc --test --no-run-tests || echo "::warning file=app.js,line=1,col=5::Failure"'
       - name: stack test
         # if: ${{ false }}
-        run: nix develop --profile .dev-profile -c sh -c 'stack test --no-nix || echo "::warning file=app.js,line=1,col=5::Failure"'
+        run: nix develop --profile .dev-profile -c sh -c 'stack test --system-ghc || echo "::warning file=app.js,line=1,col=5::Failure"'
