Allow test failures on CI again

diff --git a/.github/workflows/nix-based-build.yaml b/.github/workflows/nix-based-build.yaml
--- a/.github/workflows/nix-based-build.yaml
+++ b/.github/workflows/nix-based-build.yaml
@@ -47,4 +47,4 @@ jobs:
         run: nix develop --profile .dev-profile -c stack build --nix --no-nix-pure --test --no-run-tests
       - name: stack test
         # if: ${{ false }}
-        run: nix develop --profile .dev-profile -c stack test --nix --no-nix-pure
+        run: nix develop --profile .dev-profile -c sh -c 'stack test --nix --no-nix-pure || echo "::warning file=app.js,line=1,col=5::Failure"'
