CI: Don't use stack --nix
I think it caused trouble with nested nix shells

diff --git a/.github/workflows/nix-based-build.yaml b/.github/workflows/nix-based-build.yaml
--- a/.github/workflows/nix-based-build.yaml
+++ b/.github/workflows/nix-based-build.yaml
@@ -23,23 +23,26 @@ jobs:
           signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
           # If you chose API tokens for write access OR if you have a private cache
           authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
+      - uses: haskell/actions/setup@v1
+        with:
+          ghc-version: '8.8.4' # Exact version of ghc to use
+          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
+          enable-stack: true
+          stack-version: 'latest'
       - uses: actions/cache@v2.1.5
         name: Cache ~/.stack
         with:
           path: ~/.stack
-          key: ${{ runner.os }}-${{ matrix.ghc }}-stack-${{ hashFiles('stack.yaml.lock') }}
+          key: ${{ runner.os }}-${{ matrix.ghc }}-non-nix-stack-${{ hashFiles('stack.yaml.lock') }}
           restore-keys: |
-            ${{ runner.os }}-${{ matrix.ghc }}-stack
+            ${{ runner.os }}-${{ matrix.ghc }}-non-nix-stack
       - name: Initial nix develop
         run: nix develop --profile .dev-profile -c sh -c 'which stack; which gf; echo $GF_LIB_PATH'
       - name: stack deps
-        run: nix develop --profile .dev-profile -c stack build --nix --only-dependencies
+        run: nix develop --profile .dev-profile -c stack build --no-nix --only-dependencies
       - name: stack build
         # if: ${{ false }}
-        # TODO: Don't use --nix. Use actions/haskell instead
-        # Or just do it without nix and let stack install ghc
-        # but then we don't get other fancieness from haskell actions
-        run: nix develop --profile .dev-profile -c sh -c 'stack build --nix --test --no-run-tests || echo "::warning file=app.js,line=1,col=5::Failure"'
+        run: nix develop --profile .dev-profile -c sh -c 'stack build --no-nix --test --no-run-tests || echo "::warning file=app.js,line=1,col=5::Failure"'
       - name: stack test
         # if: ${{ false }}
-        run: nix develop --profile .dev-profile -c sh -c 'stack test --nix || echo "::warning file=app.js,line=1,col=5::Failure"'
+        run: nix develop --profile .dev-profile -c sh -c 'stack test --no-nix || echo "::warning file=app.js,line=1,col=5::Failure"'
